name: 'NPM audit'
description: 'Runs NPM audit fix and created a Markdown output on what changed'
author: 'susnux'

# Define your inputs here.
inputs:
  working-directory:
    description: 'The directory where to run npm audit'
    required: false
    default: ''
  fix:
    description: "If also 'npm audit fix' should be run. Otherwise just the Markdown output is generated."
    required: false
    default: true

# Define your outputs here.
outputs:
  markdown:
    description: "Formatted output what can be fixed with 'npm audit fix'"

runs:
  using: node20
  main: dist/index.js
